import Image from 'next/image';
import { ArrowRight, ArrowUpRight, CheckCircle2, FileCheck2, Landmark, ShieldCheck, Users, Clock3, Mail, MapPin } from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import { services } from '@/lib/services';
import Navbar from '@/components/Navbar';
import Reveal from '@/components/Reveal';
import ContactForm from '@/components/ContactForm';

const pillars: [string,string,string,LucideIcon][]=[['01','Expert Guidance','Professionals who understand the UAE regulatory environment.',ShieldCheck],['02','Tailored Solutions','Support designed around the requirements of your business.',CheckCircle2],['03','Comprehensive Support','From documentation and registration through ongoing needs.',FileCheck2],['04','Time Efficiency','We handle supporting processes so you can focus on operations.',Clock3]];
const process=[['01','Understand','We learn about your business and requirements.'],['02','Assess','We identify financial, compliance and operational needs.'],['03','Solve','We develop the appropriate service approach.'],['04','Support','We provide professional support through the process.']];

export default function Home(){return <main id="top">
<Navbar/>
<section className="hero">
  <div className="hero-image" aria-hidden="true"></div><div className="hero-shade"></div>
  <div className="hero-inner"><Reveal><span className="eyebrow">UAE BUSINESS SUPPORT · FINANCIAL SOLUTIONS</span><h1>Your business<br/><em>deserves</em><br/>clarity.</h1><p className="hero-copy">Accounting, tax, audit, compliance and business support — delivered with a clear understanding of the UAE business environment.</p><div className="actions"><a className="gold-btn" href="#services">Explore our services <ArrowRight/></a><a className="hero-link" href="#contact">Talk to an expert <ArrowUpRight/></a></div></Reveal></div>
  <div className="hero-proof"><span>01 <b>UAE FOCUS</b><small>Local expertise</small></span><span>02 <b>END-TO-END</b><small>Business support</small></span><span>03 <b>YOUR GROWTH</b><small>Our commitment</small></span></div>
  <div className="hero-side"><span>STRATEGY</span><span>COMPLIANCE</span><span>GROWTH</span></div>
</section>

<section id="about" className="about section-light"><Reveal><div className="split-head"><div><span className="kicker">01 / ABOUT ATASCENT</span><h2>More than<br/><span>accounting.</span></h2></div><div className="about-copy"><p>Atascent provides expert financial, compliance and business support for companies operating in the UAE — helping businesses stay organized, compliant and focused on what matters.</p><a className="dark-link" href="#contact">Start a conversation <ArrowUpRight/></a></div></div><div className="about-media"><div className="about-photo"></div><div className="about-note"><span>COMPLIANCE TODAY.</span><strong>OPPORTUNITY<br/>TOMORROW.</strong></div></div></Reveal></section>

<section id="services" className="services section-dark"><Reveal><div className="service-intro"><div><span className="kicker">02 / OUR SERVICES</span><h2>Comprehensive support<br/><em>for your business.</em></h2></div><div><p>From accounting and audit to tax and business support, our services are designed around the needs of businesses operating in the UAE.</p><a className="gold-text" href="#contact">Discuss your requirements <ArrowUpRight/></a></div></div><div className="service-grid">{services.map(({number,title,short,icon:Icon,slug})=><a className="service-card" href={`/services/${slug}`} key={slug}><div className="service-icon"><Icon/></div><span className="service-number">{number}</span><h3>{title}</h3><p>{short}</p><span className="service-card-link">View service <ArrowUpRight/></span></a>)}</div></Reveal></section>

<section className="uae-banner"><div className="uae-photo"></div><div className="uae-copy"><span className="kicker">03 / UAE FOCUS · GLOBAL OUTLOOK</span><h2>Rooted in the UAE.<br/><em>Ready for the world.</em></h2><p>We support businesses across the UAE, including Mainland, DMCC and other Free Zones, while helping them navigate financial and compliance needs with confidence.</p><div className="jurisdictions"><span>Mainland</span><span>DMCC</span><span>Free Zones</span><span>Global Business</span></div></div><div className="world-lines"><i></i><i></i><i></i><b>UAE</b></div></section>

<section id="why" className="why section-light"><Reveal><div className="why-head"><div><span className="kicker">04 / WHY CHOOSE ATASCENT</span><h2>A partner that<br/><span>understands business.</span></h2></div><p>Professional support should remove complexity, not add another layer to it.</p></div><div className="pillar-grid">{pillars.map(([n,t,d,Icon])=><article key={n}><span className="pillar-num">{n}</span><Icon/><h3>{t}</h3><p>{d}</p></article>)}</div></Reveal></section>

<section className="process section-cream"><Reveal><span className="kicker">05 / HOW WE WORK</span><div className="process-head"><h2>Simple on the surface.<br/><em>Thorough underneath.</em></h2><p>A structured approach keeps communication clear and the work moving.</p></div><div className="process-grid">{process.map(([n,t,d],i)=><article key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div>{i<3&&<ArrowRight/>}</article>)}</div></Reveal></section>

<section id="insights" className="insights section-dark"><Reveal><div className="insight-title"><span className="kicker">06 / INSIGHTS</span><h2>Useful thinking<br/><em>for UAE business.</em></h2><a className="gold-text" href="#contact">Talk to our team <ArrowUpRight/></a></div><div className="insight-strip"><span>Corporate Tax</span><span>VAT</span><span>Accounting</span><span>Audit</span><span>Compliance</span></div></Reveal></section>

<section id="contact" className="contact-section"><div className="contact-photo"></div><div className="contact-overlay"></div><div className="contact-inner"><Reveal><div className="contact-copy"><span className="kicker">07 / LET’S TALK</span><h2>Tell us about<br/><em>your business.</em></h2><p>Whether you need help with accounting, tax, audit or another business support service, tell us what you need and we’ll help you identify the right next step.</p><div className="contact-details"><span><Mail/>info@atascent.com</span><span><MapPin/>Sharjah Publishing City Free Zone, Sharjah, United Arab Emirates</span></div><div className="contact-promise"><CheckCircle2/> Confidential enquiry <CheckCircle2/> Clear next steps <CheckCircle2/> No obligation</div></div></Reveal><Reveal><ContactForm/></Reveal></div></section>

<footer className="footer"><div className="footer-main"><div className="footer-brand"><a className="brand" href="#top"><Image src="/atascent-logo.webp" alt="Atascent" width={46} height={46}/><span>Atascent</span></a><p>Expert business support & financial solutions in UAE.</p></div><div className="footer-col"><small>COMPANY</small><a href="#about">About</a><a href="#why">Why Atascent</a><a href="#insights">Insights</a><a href="#contact">Contact</a></div><div className="footer-col"><small>SERVICES</small>{services.slice(0,6).map(({number,title,slug})=><a key={number} href={`/services/${slug}`}>{title}</a>)}</div><div className="footer-col"><small>CONTACT</small><a href="mailto:info@atascent.com">info@atascent.com</a><span>Sharjah Publishing City Free Zone,<br/>Sharjah, UAE</span><a href="#contact" className="footer-cta">Start an enquiry <ArrowUpRight/></a></div></div><div className="footer-bottom"><span>© 2026 Atascent. All rights reserved.</span><span>UAE · MAINLAND · FREE ZONES · GLOBAL BUSINESS</span><span>Privacy · Terms · Cookies</span></div></footer>
</main>}
